### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by Shura4eburek** [NightStrang6r/RamblerAutoReg#2]
![изображение](https://user-images.githubusercontent.com/69597036/229370508-346f5c41-8aaf-4890-bb09-08d9de826456.png)
This problem has appeared. Chrome opens, the site opens, but. The page does not have time to load, as the script already starts to fill in the data, so the input fields remain empty and registration fails.

**Comment by Shura4eburek** [comment]
Fixed on my fork

**Comment by DaIneer** [comment]
как ты исправил ошибку?

**Comment by NightStrang6r** [comment]
Fixed on v1.2.0
